apiVersion: v1
kind : Secret
metadata :
  name: backend-Secret
data:
  # database_url: "cG9zdGdyZXM6Ly9hZG1pbjpwYXNzd29yZEBsb2NhbGhvc3QvNTQzMgo="
  # --------
  # config maps as configuration files(.env files)
  .env: "REFUQUJBU0VfVVJMID0gSkRMS1NKRklKRklPRUoKUE9SVCA9IDMwMDAKUFVCTElDX0tFWSA9IENETktKTlVFRkhPVURPRklKQQ=="